### ISSUE TITLE
i have tried to load example anims in api gui ingame, it gave console error

### ISSUE THREAD

**Issue by Dizcordum** [buu342/GMod-BlenderLuaAnimationsAPIExport#2]
![image](https://user-images.githubusercontent.com/68729538/204806607-6aff4e8e-2a55-45a9-9035-de8b593c559e.png)

ive tried to rename it to txt so the gui can look for it but it doesnt work

**Comment by buu342** [comment]
I have downloaded the latest commit on this repository, as well as the latest in JetBoom's API repository. I mounted the animation system like so:
1) I put the files from JetBoom's repo in the following path: `lua/autorun/animationsapi`
2) I created a lua file in `lua/autorun`, and added the following:
```lua
AddCSLuaFile("animationsapi/cl_boneanimlib.lua")
AddCSLuaFile("animationsapi/cl_animeditor.lua")
if CLIENT then
    include("animationsapi/cl_boneanimlib.lua")
    include("animationsapi/cl_animeditor.lua")
end
if SERVER then
    include("animationsapi/boneanimlib.lua")
end
```
3) I added the animation files from my repo, put them inside `lua/autorun/animations`. I had to rename `sample anim.lua` to `sample_anim.lua`.
4) I added the following to the above lua file, AFTER all the includes as these files are reliant on `RegisterLuaAnimation` from `sh_boneanimlib.lua`:
```lua
AddCSLuaFile("animations/SniperReload.lua")
AddCSLuaFile("animations/sample_anim.lua")
include("animations/SniperReload.lua")
include("animations/sample_anim.lua")
```
5) Booted up sandbox. No errors in the console
6) I tested the animations both with a custom SWEP and by typing `animate` in the console and loading the registered animations. They all worked with zero issues.

You'll need to give me a bit more information regarding your process. Are you using the latest up to date version of the API? Or are you using one of the modified versions from other addons (such as PAC3)? Have you tried disabling all addons first to ensure one of them isn't messing with the animation API?

**Comment by Dizcordum** [comment]
![image](https://user-images.githubusercontent.com/68729538/206678976-0f49b0bf-aa6d-40c9-b8bc-162750eb2013.png)
![image](https://user-images.githubusercontent.com/68729538/206679113-f21a2d1b-0d40-4e96-b171-004b212ecf36.png)
![image](https://user-images.githubusercontent.com/68729538/206679178-68956c9a-5c25-4f03-b278-01948bc5b9ad.png)
![image](https://user-images.githubusercontent.com/68729538/206680206-d99f3b31-c03a-4a19-b311-fdad4659dcc3.png)
i thought it was path placement mistake, but i did exactly the same you writed here
placed it all ingame lua folder
created lua with include lines
added lines to sh_boneanimlib.lua
and it still gives me error about "tInfo" line

**Comment by Dizcordum** [comment]
i placed anims in same folder as api code and it worked somewhat
![image](https://user-images.githubusercontent.com/68729538/206681469-570d0b03-d93b-412b-b43d-3c865951e47a.png)
also changed the path

**Comment by buu342** [comment]
Sorry yeah, I was doing the includes from memory, I forgot about `sh_boneanimlib.lua`!
```lua
AddCSLuaFile("animationsapi/cl_boneanimlib.lua")
AddCSLuaFile("animationsapi/cl_animeditor.lua")
AddCSLuaFile("animationsapi/sh_boneanimlib.lua")
if CLIENT then
    include("animationsapi/cl_boneanimlib.lua")
    include("animationsapi/cl_animeditor.lua")
end
if SERVER then
    include("animationsapi/boneanimlib.lua")
end
include("animationsapi/sh_boneanimlib.lua")
```
would be correct.
